language: cpp
sudo: false

addons:
  apt:
    packages:
      libc6-i386

env:
  global:
    - GCC_DIR="$HOME/gcc-arm-none-eabi-5_4-2016q3"
    - GCC_URL="https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q3-update/+download/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2"
    
    - XDCTOOLS_DIR="$HOME/ti/xdctools_3_32_00_06_core"
    - TIRTOS_DIR="$HOME/ti/tirtos_tivac_2_16_01_14"
    - TIRTOS_URL="http://software-dl.ti.com/dsps/dsps_public_sw/sdo_sb/targetcontent/tirtos/2_16_01_14/exports/tirtos_tivac_setuplinux_2_16_01_14.bin"

cache:
  directories:
    - $GCC_DIR
    - $XDCTOOLS_DIR
    - $TIRTOS_DIR

install:
  - if [ ! -d $XDCTOOLS_DIR ] || [ ! -d $TIRTOS_DIR ]; then wget $TIRTOS_URL -O tirtos.bin; ./tirtos.bin --mode unattended; fi
  - if [ ! -d $GCC_DIR ]; then wget $GCC_URL -O gcc.tar.bz2; tar xfj gcc.tar.bz2 -C $HOME; fi
  - export PATH=$PATH:$GCC_DIR/bin

script:
  - make